# Generated by Django 4.1.7 on 2023-04-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_performance_vote_comfort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comfort_average',
            new_name='pricing_average',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='comfort',
            new_name='pricing',
        ),
    ]
