# Generated by Django 4.1.7 on 2023-11-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
